### ISSUE TITLE
Disable directly pushing to master

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#571]
Allowing developers to directly push to the master may result in unreviewed code to enter the master branch which can be a source of bugs.
Instead enforce that code changes can only enter the master branch using MR

https://docs.gitlab.com/ee/user/project/protected_branches.html#require-everyone-to-submit-merge-requests-for-a-protected-branch

When this has been enforced we can also restrict the pipelines to only run on branches which have a MR associated:
```
workflow:
  rules:
    # Only run the pipeline when a MR is created
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
```
